### ISSUE TITLE
supported embedding models

### ISSUE THREAD

**Issue by Jeru2023** [aurelio-labs/semantic-router#103]
fastembed only support very limited models, will you change implementation to support all huggingface embedding models?

**Comment by Jeru2023** [comment]
I've hardcoded huggingface.py to replace embedding model, not elegant though, better set model name as parameter.

**Comment by ashraq1455** [comment]
@Jeru2023 we have recently added a HuggingFaceEncoder to enable support for embedding models on Hugging Face. You can use it as follows:
```python
from semantic_router.encoders import HuggingFaceEncoder

encoder = HuggingFaceEncoder(name="sentence-transformers/all-MiniLM-L6-v2")
```
