### ISSUE TITLE
Error for 05 local execution notebook in Colab

### ISSUE THREAD

**Issue by jamescalam** [aurelio-labs/semantic-router#107]
When running in Colab I see this error for llama.cpp

<img width="795" alt="image" src="https://github.com/aurelio-labs/semantic-router/assets/35938317/9759ebc8-431f-4a4b-9e15-ff7bd0884f37">

**Comment by bruvduroiu** [comment]
Hey @jamescalam , I can't replicate this on [ae18c7](https://github.com/aurelio-labs/semantic-router/commit/ae18c73281e291d2fdde5f889ef019107b7d64cc). Can you provide some more information please?

**Comment by Siraj-Aizlewood** [comment]
Fixed in: https://github.com/aurelio-labs/semantic-router/pull/157
