### ISSUE TITLE
Idea - Remove method for Route Layer

### ISSUE THREAD

**Issue by Saul-the-engineer** [aurelio-labs/semantic-router#116]
It'd be really nice to have a method that removes a route from RouteLayer. It would allow for modifying the object without reinitializing it.

**Comment by jamescalam** [comment]
I agree, we'll get this added!

**Comment by Siraj-Aizlewood** [comment]
It looks like this is now implemented via the `RouteLayer.delete()` method. Please let me know if it's okay to close.
