### ISSUE TITLE
LlamaCppEncoder

### ISSUE THREAD

**Issue by alfredwallace7** [aurelio-labs/semantic-router#118]
First of all, thanks for sharing this great project!
I needed to use local quantized models and **LlamaCppEncoder.py** seems missing in:
aurelio-labs/semantic-router/tree/main/semantic_router/encoders/
which results for me in the following error:
ImportError: cannot import name 'LlamaCppEncoder' from 'semantic_router.encoders'
I did install "semantic-router[local]" but might be missing something else.
Any advice would be greatly appreciated.

**Comment by jamescalam** [comment]
Hi @alfredwallace7 there was a typo in the documentation, it is `LlamaCppLLM` _not_ `LlamaCppEncoder` — you can follow  [this guide](https://github.com/aurelio-labs/semantic-router/blob/main/docs/05-local-execution.ipynb) for the correct usage pattern — lmk if that helps, I'm pushing a quick fix to the readme where the `LlamaCppEncoder` typo is

**Comment by alfredwallace7** [comment]
It does solve the problem, thanks! I thought "LlamaCppEncoder" could enable a quantized version of the encoder for better CPU performances.
