### ISSUE TITLE
Compatibility with latest OpenAI, langchain ?

### ISSUE THREAD

**Issue by cwe6279** [aurelio-labs/semantic-router#133]
would love to give this a try but recently had to update langchain, openai, tiktoken and pinecone-client to most recent release due to issues and running 3.11
At the moment it gives a pydantic compatibility issue in 3.11 on debian:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
canopy-sdk 0.6.0 requires pydantic<2.0.0,>=1.10.7, but you have pydantic 2.6.0 which is incompatible.
canopy-sdk 0.6.0 requires tiktoken<0.4.0,>=0.3.3, but you have tiktoken 0.5.2 which is incompatible.

I cant downgrade due to other openai and langchain dependencies and simply adding import causes a failure

**Comment by jamescalam** [comment]
seems like `canopy-sdk` is causing the conflicts, could I suggest installing canopy in a different environment? Afaik latest langchain versions also require pydantic v2

**Comment by cwe6279** [comment]
ok yeah this cleared the pip install error - thx...   stuck me with another one "No module named '_bz2'" but I think that's just my linux environment having some issues with venv

**Comment by cwe6279** [comment]
thanks for the quick reply, excited to give it a try after a rebuild of python for it worked out 👍 

Can

**Comment by jamescalam** [comment]
awesome! lmk how it goes, would also recommend that whatever you do, should check out the [optimization notebook](https://github.com/aurelio-labs/semantic-router/blob/main/docs/06-threshold-optimization.ipynb) for best results

**Comment by cwe6279** [comment]
thanks for the prompt responses- been using it and it's a great RAG enhancement!  very nice work  (also a big canopy fan).  I do have one question specifically I was trying to solve for... was previously using a websocket to summarize a chat and send a slack message, but aiming to try that here; it "works" technically, but struggling to figure a way to only execute the agent if some conditions are present... for example in the chat history we must have gathered some minimum {email} and/or {phone} and {name}" before passing this to the agent for an action.... I am thinking of adding a call to the LLM just to do this check but Ill then have 3 calls (one for HYDE + RAG + for that) which is a lot of performance and overhead for a single chat.  Next on my to dos is the optimizations
