### ISSUE TITLE
Ask for a feature.

### ISSUE THREAD

**Issue by knownbymanoj** [aurelio-labs/semantic-router#136]
I wanted to ask you if dynamic routing being used needs just OpenAI encoding model for finding the dynamic routes, and
does the dynamic routing support multiple routes triggering if the query asked contains info about multiple routes?

**Comment by bruvduroiu** [comment]
Hi, feel free to use any of [these encoders](https://github.com/aurelio-labs/semantic-router/tree/main/semantic_router/encoders) with Dynamic Routes.

If a query contains multiple routes, you should first split the query using a semantic splitter and compare each of the splits to judge routes.

Further reading:

[Using Dynamic Routes - semantic-router](https://github.com/aurelio-labs/semantic-router/blob/main/docs/02-dynamic-routes.ipynb)
[Split Conversation by Topic - semantic-router](https://github.com/aurelio-labs/semantic-router/blob/main/docs/examples/conversation-topic-splitter.ipynb)
