### ISSUE TITLE
Supporting `OPENAI_ORGANIZATION` variable

### ISSUE THREAD

**Issue by maxyousif15** [aurelio-labs/semantic-router#141]
Is it possible to add support for the `OPENAI_ORGANIZATION` environment variable? Alternatively, is it possible to pass an initialised client object, instead of re-instantiating the openAI client every time? 

This request is only relevant for the `OpenAIEncoder` class.

**Comment by bruvduroiu** [comment]
This is possible for the `OpenAIEncoder`. Would you be able to help with a contribution to this feature?

**Comment by Siraj-Aizlewood** [comment]
I think this is already supported via the `OPENAI_ORG_ID` environment variable in the OpenAI client.

- In `OpenAIEncoder`, we run: `self.client = openai.Client(api_key=api_key)`.
- Then in `openai > _client.py`, we have: `Client = OpenAI`.
- Finaly in the OpenAI class: 
  ```
    if organization is None:
        organization = os.environ.get("OPENAI_ORG_ID")
  ```
 
So I think it should work simply by setting the `OPENAI_ORG_ID` environment variable.

However, maybe we can implement passing an `org_id` argument to the `OpenAIEncoder.__init__` method, in case different encoder/client instances are required to have different organizations? It could be useful in those cases.

**Comment by Siraj-Aizlewood** [comment]
@maxyousif15, please let us know if using the `OPENAI_ORG_ID` environment variable is sufficient for your needs, or if the `org_id` argument would be preferred.

**Comment by maxyousif15** [comment]
I think the `org_id` argument would be a more general & better solution. Happy to help make this change. Do you have documentation on the process of contributing to this project?

**Comment by Siraj-Aizlewood** [comment]
Hi @maxyousif15, we do now! Please see `CONTRIBUTING.md`, here: https://github.com/aurelio-labs/semantic-router/blob/main/CONTRIBUTING.md

Thank you very much for offering to contribute to the project :-)

**Comment by maxyousif15** [comment]
I've created a draft PR here https://github.com/aurelio-labs/semantic-router/pull/159.
I'll try to regularly check for feedback whenever I get time. I would suggest to continue the communication on the PR.

**Comment by Siraj-Aizlewood** [comment]
Above PR merged. Issues resolved.
