### ISSUE TITLE
TypeError: Object of type Client is not JSON serializable. Using Cohere LLM 

### ISSUE THREAD

**Issue by yusufola** [aurelio-labs/semantic-router#144]
When trying to save the route configuration to a file using the `to_file` method in the `Layer` class, a TypeError is raised with the message _"Object of type Client is not JSON serializable"_.

```
functions = [get_time]

routes = []

llm = CohereLLM(name="command-nightly")

for function in functions:
    route = Route.from_dynamic_route(entity=function, llm=llm)
    routes.append(route)

layer_config = LayerConfig(routes=routes, encoder_type="cohere", encoder_name="embed-english-v3.0")
layer_config.to_file("output/layer_config.json")
```
**Expected behavior** 
The to_file method should successfully serialize the Layer object and its routes (including any Client objects) to a file in JSON or YAML format.

Error 
<img width="1044" alt="Screenshot 2024-02-12 at 10 33 50 PM" src="https://github.com/aurelio-labs/semantic-router/assets/23318046/02367e68-86bb-493a-ba46-55100f0321fd">

**Comment by Siraj-Aizlewood** [comment]
Hi @yusufola, I'm investigating this issue. Thank you for bringing it to our attention.

**Comment by Siraj-Aizlewood** [comment]
@yusufola, I'm making some updates in a branch to bug fix this. It's in the early testing and review phase. Will let you know when we have something more concrete.

**Comment by yusufola** [comment]
Many Thanks @Siraj-Aizlewood

**Comment by Siraj-Aizlewood** [comment]
@yusufola this has been fixed and merged into main now. Please let us know if you run into any additional issues.

**Comment by Siraj-Aizlewood** [comment]
I forgot to mention: If this resolves things, please close the Issue :-)
