### ISSUE TITLE
Is there a limit to the length of utterances?

### ISSUE THREAD

**Issue by fredowashere** [aurelio-labs/semantic-router#148]
Hey guys,

sorry for bothering you.
I didn't try the library yet, but I couldn't find the following info in the doc: **what's the limit of utterances length?**

Thanks in advance,
Fredo

**Comment by bruvduroiu** [comment]
No current utterance limit imposed by the library, however, semantic similarity is computed between query and your list of utterances, so you might find a physical boundary is the size of utterance vectors in memory

**Comment by Siraj-Aizlewood** [comment]
Closing as this seems to be resolved. Let me know if we should reopen.
