### ISSUE TITLE
running on Raspberry PI 5 ?

### ISSUE THREAD

**Issue by ciaotesla** [aurelio-labs/semantic-router#151]
I wanted to know if there are any limitations on running Semantic Router on a RPI5.

Currently I am running CrewAI and Ollama LLM locally "openhermes" on a RPI5.
I wanted to speed up the CrewAI Agent work with Ollama LLM and seems Semantic Router a good choice.
The Agents are used to make some internet search on a topic and the LLM does some work on the result of the search.
Any simple example on how to set it up locally and if it makes sense? 
Also would this allow me to use larger LLMs?
thx

**Comment by bruvduroiu** [comment]
We currently support local execution via [ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp). An example can be found here https://github.com/aurelio-labs/semantic-router/blob/main/docs/05-local-execution.ipynb
