### ISSUE TITLE
Question about attributes of RouteChoice

### ISSUE THREAD

**Issue by cyc00518** [aurelio-labs/semantic-router#152]
Hi, Thanks for sharing such a good concept!

Why my attributes of RouteChoice are all `None` except name?
`RouteChoice(name='politics', function_call=None, similarity_score=None, trigger=None)`

`similarity_score` should represent the similarity score between the input and the utterance, right?
Furthermore, what does `trigger`  mean?

Thanks!

**Comment by jamescalam** [comment]
Correct on `similarity_score`; although we don't use it anymore, it will likely be removed. For `trigger`, this was no longer used and has now been removed (as of `0.0.28`) The `function_call` parameter is used by [dynamic routes](https://github.com/aurelio-labs/semantic-router/blob/main/docs/02-dynamic-routes.ipynb).
