### ISSUE TITLE
02-Dynamic-Router.ipynb Error after `rl.add(time_route)`

### ISSUE THREAD

**Issue by antonsapt4** [aurelio-labs/semantic-router#191]
Hi, I tried to use the the Notebook [docs/02-dynamic-routes.ipynb](https://github.com/aurelio-labs/semantic-router/blob/main/docs/02-dynamic-routes.ipynb) on Google Colab and use Cohere api key as embedding model. 
The static route works fine, but when using dynamic router it throw error on the last cell (as Screenshot)

Error:
```
2024-03-10 07:38:16 WARNING semantic_router.utils.logger No LLM provided for dynamic route, will use OpenAI LLM default. Ensure API key is set in OPENAI_API_KEY environment variable.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-11-f02444f1667a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 out = rl("what is the time in new york city?")
      2 get_time(**out.function_call)

1 frames
[/usr/local/lib/python3.10/dist-packages/semantic_router/llms/openai.py](https://localhost:8080/#) in __init__(self, name, openai_api_key, temperature, max_tokens)
     27         api_key = openai_api_key or os.getenv("OPENAI_API_KEY")
     28         if api_key is None:
---> 29             raise ValueError("OpenAI API key cannot be 'None'.")
     30         try:
     31             self.client = openai.OpenAI(api_key=api_key)

ValueError: OpenAI API key cannot be 'None'.
```

For some reason it not detect that already use cohere like in the static route.

<img width="1515" alt="image" src="https://github.com/aurelio-labs/semantic-router/assets/142082912/83503dfa-cfa9-4f0b-982a-335504417b3c">

**Comment by jamescalam** [comment]
Hey can you try setting the OPENAI_API_KEY env var? Ie os.environ[“OPENAI_API_KEY”] = “your api key” — that should help :)

**Comment by jamescalam** [comment]
Hi @antonsapt4 yes this is the expected behaviour.
1. Yes an LLM (ie OpenAI in this example) is required for dynamic routes, whereas static routes use embedding models (ie Cohere in this example) only.
2. As above, the dynamic route requires an LLM, whereas static route does not.
3. Yes there is [an example here](https://github.com/aurelio-labs/semantic-router/blob/main/docs/examples/ollama-local-execution.ipynb).

I hope those help!
