### ISSUE TITLE
HugginFaceEndpoint encoder integration

### ISSUE THREAD

**Issue by alessioserra** [aurelio-labs/semantic-router#222]
Hi everyone, I would like to use semantic routing using a **HuggingFace private endpoint** (with URL and API key) as the encoder. Is it possible to do this, or does it require some kind of integration? If yes, what would be the best strategy to implement it? 

Thanks to all :)
Alessio

**Comment by jamescalam** [comment]
Hi @alessioserra, this is currently not possible as our `HuggingFaceEncoder` is built to work with local HF models, not HF endpoints — it'd be great to get them integrated though! If you'd like to implement it would join the other `encoders`, something like a `HFEndpointEncoder`?

**Comment by alessioserra** [comment]
Hi @jamescalam, I have already develop a custom HFEndpointEncoder, I would be happy to add it to your project :) 
I'll review the code and I'll do a PR this week if it is OK for you

**Comment by jamescalam** [comment]
hey @alessioserra — that'd be awesome, looking forward to it!

**Comment by andreped** [comment]
> Hi @jamescalam , I have just created the PR: #241
> 
> Have a nice day! :)

Man I just love open-source! I hope you have a nice day as well, @alessioserra! :] Great job on the PR. Looks great!
