### ISSUE TITLE
Add Google's embedding models as an Encoder

### ISSUE THREAD

**Issue by smwitkowski** [aurelio-labs/semantic-router#223]
I'm interested in using Google's embedding models with Semantic Router, but I noticed there isn't a Google Encoder class.

I'd love to help develop a base encoder for Google models, namely those in the textembedding-gecko family.

**Comment by smwitkowski** [comment]
If this is in-scope, I've drafted a pull request for this.

https://github.com/aurelio-labs/semantic-router/pull/224

**Comment by jamescalam** [comment]
thanks @smwitkowski! I've merged your PR #224 and released this as part of `semantic-router==0.0.31`
