### ISSUE TITLE
Add google cloud dependencies

### ISSUE THREAD

**Issue by joaomsimoes** [aurelio-labs/semantic-router#238]
With the new release the google cloud dependencies are not being installed 

`ModuleNotFoundError: No module named 'google.cloud'`

**Comment by jamescalam** [comment]
Ah, we need a `try-except` within the `GoogleEncoder`, we'll add quickly

**Comment by jamescalam** [comment]
@joaomsimoes thanks for raising the issue! Fix is live with `0.0.32` https://github.com/aurelio-labs/semantic-router/releases/tag/v0.0.32
