### ISSUE TITLE
Bug in Python3.12 "The api_key client option must be set either by passing api_key"

### ISSUE THREAD

**Issue by hookenful** [aurelio-labs/semantic-router#243]
Why does I have this error only in Python3.12? It 3.11 there is no such error.
Why does it forces me to provide api key for OpenAI even if I don't use it. 
Can I somehow prevent this behavior?

`OpenAIError('The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable')`

**Comment by zahid-syed** [comment]
Could you clarify where this error arises? I have tried using the Route_Layer and I don't see this error with Cohere Encoder. Please give a detailed account of the the conditions so that the error can be reproduced and troubleshooted.
