### ISSUE TITLE
Conflict with langchain-cohere package

### ISSUE THREAD

**Issue by driviere27** [aurelio-labs/semantic-router#267]
I love the semantic router but a drawback is that it's cohere dependancy is cohere 4.57 whereas if you want to use langchain-cohere (in order to leverage the reranker for example), it requires cohere 5.3 and up! It seems like we essentially need to choose between the SR and the reranker... it would be great if they could work in tandem!

**Comment by jamescalam** [comment]
This should be resolved with #280 — I'm pushing this change to version `0.0.41`

I'll close the issue for now, let us know if you run into any problems!

**Comment by jamescalam** [comment]
update: `0.0.41` is out https://github.com/aurelio-labs/semantic-router/releases/tag/v0.0.41

**Comment by driviere27** [comment]
Awesome!
