### ISSUE TITLE
New Semantic Router 0.0.41 conflicts with Tiktoken-0.7.0 which is required for langchain-openai

### ISSUE THREAD

**Issue by driviere27** [aurelio-labs/semantic-router#287]
New Semantic Router 0.0.41 conflicts with Tiktoken-0.7.0 which is required for langchain-openai.

**Comment by driviere27** [comment]
*Most recent version of langchain-openai

**Comment by jamescalam** [comment]
these langchain conflicts... 😅 — pushing a solution asap

**Comment by jamescalam** [comment]
@driviere27 I've pushed a fix in `0.0.43` #289 — I've modified a few deps to be more flexible, but lmk if you find more issues — we appreciate you flagging these for us!
https://github.com/aurelio-labs/semantic-router/releases/tag/v0.0.43

**Comment by driviere27** [comment]
> these langchain conflicts... 😅 — pushing a solution asap

I know they're endless! haha
