### ISSUE TITLE
Adding License to PYPI package release

### ISSUE THREAD

**Issue by mohammedayub44** [aurelio-labs/semantic-router#337]
Hi There,

Planning to use this our enterprise environment, which does additional scanning of PYPI packages. One of the steps is scanning for licenses. It seems that it is missing the license on PYPI and I'm not able to bring this repo into our environment.  Could you  please add the license file in your pypi release. 

Thanks !

**Comment by jamescalam** [comment]
@mohammedayub44 can you check if `0.0.49` is working for you? https://github.com/aurelio-labs/semantic-router/releases/tag/v0.0.49

**Comment by mohammedayub44** [comment]
Still gives me an error. When you install and do a `pip show semantic-router` , does it show the license on your end. 
Something like below:
```bash
$ pip show langchain
Name: langchain
Version: 0.1.20
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
**License: MIT**
Location: .\Lib\site-packages
Requires: aiohttp, dataclasses-json, langchain-community, langchain-core, langchain-text-splitters, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity

```

**Comment by jamescalam** [comment]
okay thanks, I think it will be fixed with`0.0.50`, now showing:
<img width="621" alt="image" src="https://github.com/aurelio-labs/semantic-router/assets/35938317/494349ec-529b-4d18-b20a-1f43af5a8a2d">

**Comment by jamescalam** [comment]
Closing for now

**Comment by mohammedayub44** [comment]
thanks it worked.
