### ISSUE TITLE
Fix _get_all method unordered retunr tuple elements in pinecone.py when passing both prefix and metadata

### ISSUE THREAD

**Issue by Vits-99** [aurelio-labs/semantic-router#345]
Considering the _get_all method in pinecone.py, when calling it with a prefix without metadata or with metadata without a prefix everything seems fine but when using both the output indexed order for ids and metadata is not the same. For instance, let's suppose that I get 3 ids and 3 (route, utterance) pairs. It is not guaranteed that the first element of the list of ids is the id related to the first element of (route, utterance) pair. Should be fixed.

**Comment by jamescalam** [comment]
Likely fixed with #344, just waiting on confirmation from @Vits-99

**Comment by jamescalam** [comment]
Confirmed this has been resolved with #344
