### ISSUE TITLE
Add custom metadata to routes stored in Pinecone

### ISSUE THREAD

**Issue by Vits-99** [aurelio-labs/semantic-router#399]
Currently, our implementation allows storing only "sr_route" and "sr_utterance" in Pinecone. While this covers basic needs, it limits flexibility for users who may require additional context or categorization for their data. To enhance the utility and versatility of remote indexes we should include custom metadata fields. This feature would allow users to store additional data such as "position", "prompt", "type", or any other user-defined attributes alongside the existing fields

**Comment by Siraj-Aizlewood** [comment]
Will take a look at this.
