### ISSUE TITLE
Python 3.12-3.13 support?

### ISSUE THREAD

**Issue by andreped** [aurelio-labs/semantic-router#452]
As we are migrating to Python 3.13, I was not surprised to see that some libraries do not yet _officially_ support 3.13, as it is only 2 weeks old.

But I was surprised to see that Python 3.12 does not seem to be officially supported yet (see PR https://github.com/aurelio-labs/semantic-router/pull/111). What is the hold-up?

The TOML file also says that 3.12 should be supported (see [here](https://github.com/aurelio-labs/semantic-router/blob/main/pyproject.toml#L11)) but from various threads that does not seem to be the case.

**Comment by jamescalam** [comment]
@andreped it seems that `3.12` is functional unless our tests are missing something - I added test coverage for it here https://github.com/aurelio-labs/semantic-router/pull/456

We'll be looking into 3.13 soon

**Comment by andreped** [comment]
@jamescalam We have upgraded our backend to Python 3.12 and all is good.

Any update on Python 3.13?

**Comment by jamescalam** [comment]
@andreped I'm going to start on 3.13 support now — adding to `v0.1.0` release, will let you know once I have an update

**Comment by jamescalam** [comment]
@andreped added support - however anything relying on `torch` or `fastembed` will not work yet (as neither currently support `3.13`)
