### ISSUE TITLE
ImportError: cannot import name 'RouteLayer' from 'semantic_router'

### ISSUE THREAD

**Issue by komastunana** [aurelio-labs/semantic-router#484]

**Comment by jamescalam** [comment]
with `0.1.0.dev2` and up the `RouteLayer` is now `SemanticRouter` and is imported with `from semantic_router.routers import SemanticRouter`

**Comment by komastunana** [comment]
> with `0.1.0.dev2` and up the `RouteLayer` is now `SemanticRouter` and is imported with `from semantic_router.routers import SemanticRouter`

Thanks
