### ISSUE TITLE
Doc Update for semantic-router/docs/examples /function_calling.ipynb

### ISSUE THREAD

**Issue by levi-katarok** [aurelio-labs/semantic-router#65]
Just started playing around (really excited at the possibilities!), and started with the notebook function_calling.ipynb. 
In cell 2, it calls for `from semantic_router.route import Route, RouteConfig`. Within the `semantic_router/route.py` file I don't see any RouteConfig class or export, and thus causes an error. 

Was wondering if there's an updated way to do this (I see elsewhere you use RouteLayer).

Any help is appreciated!

**Comment by simjak** [comment]
@levi-katarok  thanks for the message, I have updated the notebook, and PR is ready for review:
https://github.com/aurelio-labs/semantic-router/pull/75

**Comment by levi-katarok** [comment]
Appreciate it thank!
