### ISSUE TITLE
OpenRouter Q

### ISSUE THREAD

**Issue by bramses** [aurelio-labs/semantic-router#66]
I'm unfamiliar with OpenRouter here in the LLM code. Any way to add Cohere and OpenAI as options too?

https://github.com/aurelio-labs/semantic-router/blob/main/semantic_router/utils/llm.py

**Comment by ArneJanning** [comment]
Another problem with OpenRouter is that it doesn't support Azure OpenAI.

**Comment by jamescalam** [comment]
yes, we are prioritizing adding other LLM options, expect something in the next couple of days
