### ISSUE TITLE
Route not initialising

### ISSUE THREAD

**Issue by gayuoptisol** [aurelio-labs/semantic-router#76]
python version - 3.9 (VS Code)
semantic-router version - 0.0.14
ERROR:

![image](https://github.com/aurelio-labs/semantic-router/assets/109940886/260d09be-d2e1-4fea-9f9f-b65adfd0554b)

**Comment by simjak** [comment]
@gayuoptisol  thanks for the issue! will fix it and let you know

**Comment by jamescalam** [comment]
@simjak I think this is an issue with python 3.9 specifically

**Comment by jamescalam** [comment]
we are for now not able to support py3.9 — if this is a blocker for anyone please let us know, so we can track py3.9 requests, thanks

**Comment by simjak** [comment]
@gayuoptisol the code is pushed to the main, and will be available with the latest release, let us know if the issue persists

**Comment by gayuoptisol** [comment]
@simjak Thanks for the support, i will work on it
