### ISSUE TITLE
Any plans to upgrade to pydantic 2?

### ISSUE THREAD

**Issue by stikkireddy** [aurelio-labs/semantic-router#77]
Causing version conflicts with other libraries. Was wondering if there are any plans to upgrade.

**Comment by simjak** [comment]
Yes! @stikkireddy

**Comment by 0-1CxH** [comment]
same problem, my pydantic is 2.5, cannot work with this

**Comment by adambenari** [comment]
+1

**Comment by simjak** [comment]
@stikkireddy any suggestions of how can I make compatible with Pydantic v1 and v2?

**Comment by jamescalam** [comment]
does #109 solve your issues @stikkireddy @0-1CxH @adambenari @qedpi ?

**Comment by 0-1CxH** [comment]
> does #109 solve your issues @stikkireddy @0-1CxH @adambenari @qedpi ?

Yes, it works with pydantic==2.5.2
