### ISSUE TITLE
Support for custom HF embedding model

### ISSUE THREAD

**Issue by tranhoangnguyen03** [aurelio-labs/semantic-router#78]
I see here that you are encoding the user query and compare them against the encoded utterances in each route and map the query to the closest utterance>route. Rather than using the Cohere or OpenAI embedding models and suffer the latency and expenses from calling their apis, it would be great to be able perform routing use a locally deployed embedding model from HuggingFace. This also opens up the opportunity to use custom embedding model finetuned for specific domain (health-care in my case). 

Thanks for the great project. And I can't wait to see it develop further.

**Comment by jamescalam** [comment]
We want to add this as soon as possible, we're working on it!

**Comment by jamescalam** [comment]
solved with #90
